name: Web Release

on:
  push:
    branches:  [ "main" ]

jobs:
  build:
    name: Create Web Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: gradle
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.2"
          channel: 'stable'
          cache: true
      
      - name: Get dependencies
        run: flutter pub get

      - name: Start Web Release Build
        run: flutter build web --release --web-renderer canvaskit
     
      - name: Upload Web Build Files
        uses: actions/upload-artifact@v2
        with:
          name: web-release
          path: ./build/web

  build:
    name: Build Docker Image and Deploy to Docker Hub
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Docker Login
      uses: actions/checkout@v2
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USERNAME --password-stdin

    - name: Build the Docker Image
      run: |
        docker build -t tree-webapp .
        docker tag tree-webapp $DOCKER_USERNAME/tree-webapp:latest
        docker push $DOCKER_USERNAME/tree-webapp:latest
      

