name: Flutter Web Build and Docker Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.3' # Specify your Flutter version

      - name: Get dependencies
        run: flutter pub get

      - name: Build Flutter web
        run: flutter build web --release

      - name: Login to Docker Hub
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Build Docker image
        run: docker build -t "$DOCKER_USERNAME"/"$DOCKER_REPO":latest .

      - name: Push Docker image
        run: docker push "$DOCKER_USERNAME"/"$DOCKER_REPO":latest